### ISSUE TITLE
00 -- This is Heavy -- Ben Gohlke

### ISSUE THREAD

**Issue by jcgohlke** [TheIronYard--Orlando/2015--FALL--iOS#1]
### Tasks:

* [X] [Create a Github account](https://github.com/signup)
* [X] Find and star [the class project](https://github.com/TheIronYard--Orlando/2015--FALL--iOS)
* [ ] Read [the Home page on the class wiki](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/wiki)
* [ ] [Create a new _WIP Issue_](https://github.com/TheIronYard--Orlando/2015--FALL--iOS/issues/new)
  * [ ] Named `00 -- This is Heavy -- YOUR NAME` (where `YOUR NAME` is _your_ name)
  * [ ] With this checklist as the description
* [ ] [Edit your Github profile](https://github.com/settings/profile) to provide:
  * [ ] A picture, so I can recognize your face.
  * [ ] Your full name, so I can recognize your name.
  * [ ] A valid public email address, so I can contact you if I need to.
* [ ] [Complete the "Hello World" Github guide](https://guides.github.com/activities/hello-world/)
  * [ ] Add a link to your new Github repo as a comment on your *WIP Issue*
* [ ] Complete the Code School course [Try Git](https://www.codeschool.com/courses/try-git)
  * [ ] Take a screenshot of the Try Git course when you complete it and add it as a comment to your *WIP Issue*
* [ ] Create a new repository called `TIY-Assignments`
  * [ ] Check the box to create an initial `README.md` file
  * [ ] Select the `CC0` -- "Creative Commons" license for your work
  * [ ] Add a link to your `TIY-Assignments` repo as a comment on your *WIP Issue*
* [ ] Install Xcode from the Mac App Store. Simply search for _Xcode_.
* [ ] Open Xcode. Click the _Xcode_ menu in the menubar, then choose _Preferences_. Navigate to the _Downloads_ tab and install the latest iOS documentation (currently iOS 8.3, will probably be 9.0 when class starts). Once fully downloaded, the docset should have a small checkmark next to it.
* [ ] Watch _The Long Run_ Videos on [Delve.tv](http://delve.tv)
   * [ ] [_The Long Game_, part 1](http://delve.tv/the-long-game-part-one/)
   * [ ] [_The Long Game_, part 2](http://delve.tv/the-long-game-part-2/)
* [ ] Complete the [Swift Basics](http://teamtreehouse.com/library/swift-basics) course on Treehouse.
   * [ ] Take a screenshot of your points earned for the course and add it as a comment to your *WIP Issue*
* [ ] Look at the Prework-A file for instructions on how to complete the Counter app.
   * [ ] Your counter app files should be added to your TIY-Assignments repo. Because you previously added a link to your repo to your *WIP Issue*, I will be able to see your progress as you go. Be sure to commit/push the changes you make as you work on the app.
