### ISSUE TITLE
29 -- Movie Mania -- Sam Shaw & Chris Stomp

### ISSUE THREAD

**Issue by stomp1128** [TheIronYard--Orlando/2015--FALL--iOS#259]
https://github.com/stomp1128/TIY-Assignments/pull/22

**Comment by SamuelShaw** [comment]
![new mockup 1](https://cloud.githubusercontent.com/assets/14863465/11171190/f5932450-8bb7-11e5-980e-2b59ce98d4b4.png)
![new mockup 2](https://cloud.githubusercontent.com/assets/14863465/11171191/f5a3dcc8-8bb7-11e5-980f-c5da2b3c7ec4.png)
![new mockup 3](https://cloud.githubusercontent.com/assets/14863465/11171192/f5a46bfc-8bb7-11e5-947d-528f316fe112.png)

**Comment by SamuelShaw** [comment]
### Task List

* [X] Create new  project
* [X] Add a nav bar to the view
* [X]Add a plus button to the nav bar
* [X]Add a new tableview in storyboard
* [X]Connect the plus button to tableView
* [X]Add a search bar, search button, and Cancel button to the tableView
* [X]create a detail view controller
* [X]Add an image view and labels to add the info from the cell
* [X]Add design for looks

### Code Tasks

* [X]Setup Variables
* [X]Add properties and create array(s)
* [X]Configure the tableview and tableview custom cell
* [X]Setup the omdb api for usage
