### ISSUE TITLE
29 -- Movie Mania -- Samuel Shaw

### ISSUE THREAD

**Issue by SamuelShaw** [TheIronYard--Orlando/2015--FALL--iOS#297]
### Task List

* [X] Create new  project
* [X] Add a nav bar to the view
* [X] Add a plus button to the nav bar
* [X] Add a new tableview in storyboard
* [X] Connect the plus button to tableView
* [X] Add a search bar, search button, and Cancel button to the tableView
* [X] create a detail view controller
* [X] Add an image view and labels to add the info from the cell
* [X] Add design for looks

### Code Tasks

* [X] In the movie tableview, create an empty array for movies
* [X] Set number of cells to movies in the array
* [X] Create custom cell with identifier
* [X] Uncomment code for editing the tableview
* [X] Uncomment code for prepare for segue & setup segue identifier
* [X] In movie cell, setup IBOutlets
* [X] In Choose movie file, setup IBOutlet for UISearch bar & set delegate to UISearch Bar delegate
* [X] In choose movie, also create a search function that will allow use of an api
* [X] Setup IBActions for both search and cancel
* [X] Mark choose movie class as a NSURLSessionDataDelegate and create function
* [X] Create movie object class and initialize values from the json
* [X] In movie detail controller, set image and plot description from items in the movie class

**Comment by SamuelShaw** [comment]
stomp1128/TIY-Assignments#22
