### ISSUE TITLE
45 -- Build Me Something Beautiful -- Pedro Trujillo

### ISSUE THREAD

**Issue by PedroTrujilloV** [TheIronYard--Orlando/2015--FALL--iOS#340]
# Objective
The purpose of the app is to provide a rich mobile experience for existing YYYmeal.com users to work with their grocery lists.
Users of the application are professional chefs. When planning a service for a customer, the chef will prepare a grocery list or items they need to buy in order to effectively prepare the service. This grocery list is usually specific to a service for a single customer,at a single location and on a single date. Thus it is also important that the chef have access to key information about the customer while shopping.

# Tasks 

* [ ] Design the 4 basic interfaces from  the mockups in the Requirements Document.
* [ ] User Session management 
* [ ] The first page of the application is the "list of lists". When the app starts, assuming the user has previously authenticated, the app will need to grab the list of grocery lists from the server and present them on this screen.
* [ ] The app should also grab and store the full list data for any list shown on screen for any list set for a date +/- 30 days from today.
* [ ] Clicking a list takes the user to the grocery list screen.
* [ ] After selecting a list on the front page, the app navigates to the list detail view. The user can click the Back icon at the top on the navigation bar to return to the list of lists After selecting a list on the
front page, the app navigates to the list detail view. The user can click the Back icon at the top on the navigation bar to return to the list of lists.
* [ ] The list detail shows the full grocery list with items grouped by category. Each item will typically include a quantity and item name, as well as descriptive text from the recipes the item is used in.
* [ ] The user will be able to check off grocery items as they are bought. Those items will gray out. Shaking the phone will undo the most recent change (and can be repeated up to 10 times).
* [ ] A tab bar at the bottom of the list lets the user access customer information and notes.
* [ ] Any changes made here by the user are sent back to the server (either immediately, or when the phone is next online).
* [ ] Clicking the Customer button in the tab bar at the bottom of the screen takes the user to the customer information page.
* [ ] This shows basic information including the customer's name and address, as well as notes the Chef has entered and details of the exclusions that the chef needs to be aware of. This information is not editable.
* [ ] Chefs have already asked us for the ability to make notes while they shop.
* [ ] Clicking on the notes icon on the tab bar at the bottom of the screen takes them a freeform notes area where they can enter notes for this grocery list.
* [ ] This information is not persisted back to the server at this time, but will be in the future. As such, it is important that the app store this information.
