### ISSUE TITLE
06 -- S.H.I.E.L.D. Hero Tracker -- Jen Hamilton

### ISSUE THREAD

**Issue by embryoconcepts** [TheIronYard--Orlando/2015--FALL--iOS#62]
#### Storyboard Tasks
* [x] Remove the view in the storyboard from the template
* [x] Add a Table View Controller to the canvas
* [x] Embed the above in a Navigation Controller
* [x] Add a second View Controller, to be used as the table's detail view
* [x] The table view cell prototype should display two labels. One on the left of the cell and one on the right.
    * [x] The table view cell prototype should have a disclosure indicator
    * [x] The table view cell prototype should have its reuse indentifier set (hint: this should match the identifier set in "cellForRowAtIndexPath")
* [x] The detail view should have a custom class name of "HeroDetailViewController". See the identity inspector in Interface Builder.
* [x] The detail view should have 3 labels:
    * [x] A label in the upper left corner that displays the hero's name
    * [x] A label 20 pts below the cover name label that displays the hero's homeworld
    * [x] A label the standard distance (8 pts) from the homeworld label that displays the hero's powers (be sure to set the label to _0 lines_ in the attributes inspector, as it will allow you to display more than 1 line)
    * [x] These labels should be connected to their appropriate properties in the HeroDetailViewController class.

#### Code Tasks
* [x] Remove the _ViewController.swift_ file from the project
* [x] Add a new Table View Controller subclass called _HeroTableViewController_
* [x] Add a new View Controller subclass called _HeroDetailViewController_
* [x] Add a new swift class called "Hero"
* [x] Add the _heroes.json_ file to the project
* In _HeroTableViewController_:
    * [x] Create a property to store custom _Hero_ models
    * [x] Set the title to "S.H.I.E.L.D. Hero Tracker"
    * [x] Call the private method _loadHeroes()_
    * [x] Create a private method called _loadHeroes()_
        * [x] Load the JSON file into a local array
        * [x] Create a for loop that iterates over each dictionary in the array and creates a hero object. Add each hero to the _heroes_ array property
        * [x] Sort the _heroes_ array in place to alphabetize the list by hero name
    * [x] Implement the three tableview datasource methods to get each hero in the _heroes_ array to display in the table with the name in the cell's left label and their homeworld in the cell's right label.
    * [x] Implement the _didSelectRowAtIndexPath_ tableview delegate method to transition to the detail view. Be sure to send the appropriate hero object to the detail view controller before you inititate the transition.
* In _HeroDetailViewController_:
    * [x] Create three IBOutlet properties: _nameLabel_, _homeworldLabel_, and _powersLabel_ and wire them up to the appropriate labels in the storyboard.
    * [x] Add a property called _hero_ that is a Hero optional.
    * [x] Take the name, homeworld and powers from the hero property and set them to their appropriate label onscreen.

### Hard Mode

* [ ] Add a UIImageView to the detail view to display an avatar-style image of the hero. See the screenshot _hardmode.png_ in today's folder for a guide on how to place it in the view.
* [ ] Find images for each hero on Google image search or similar, add the image files to the project, and then add a fourth key:value pair to the JSON for each hero with the filename of the associated image.
    * [ ] Add a property to the Hero model class to store this filename (as a String)
    * [ ] In the _loadHeroes()_ function, pull this value from the dictionary each time through the loop and store it in your new model property
    * [ ] In the same place in _HeroDetailViewController_ where you set the three labels, add another instruction that uses the filename property from the model object to load the appropriate image into the UIImageView.

#### Journal, Week 1
   * [x] created branch in `USERNAME.github.io` named `journal-week-1`
   * [x] created new file named `journal-week-1.md`
   * [x] commited, pushed, and opened PR to `master`
   * [x] added draft journal entry

**Comment by embryoconcepts** [comment]
https://github.com/embryoconcepts/TIY-Assignments/tree/master/06%20--%20SHIELD%20Tracker/SHIELD%20Hero%20Tracker

**Comment by embryoconcepts** [comment]
Having issues with pulling down the remote brances to Tower when it's for the wiki. This may be a unique  issue, since I can't use Github desktop. Will continue to try to work through it. https://github.com/embryoconcepts/embryoconcepts.github.io/wiki/Journal-Week-1

**Comment by jcgohlke** [comment]
@embryoconcepts sure.

**Comment by embryoconcepts** [comment]
https://github.com/embryoconcepts/TIY-Assignments/pull/7

**Comment by jholsapple** [comment]
Good job!
